import { Sparkles, Play, Pause, Square, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useSpeech } from "@/hooks/useSpeech";

interface Props {
  text: string;
}

export const AIAnalysis = ({ text }: Props) => {
  const { status, supported, play, pause, resume, stop } = useSpeech();
  const paragraphs = text.split(/\n\n+/).map((p) => p.trim()).filter(Boolean);

  const handlePrimary = () => {
    if (status === "speaking") pause();
    else if (status === "paused") resume();
    else play(text);
  };

  return (
    <section className="rounded-xl bg-card border border-border shadow-card p-6 md:p-8">
      <div className="flex items-start justify-between gap-4 flex-wrap mb-1">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          <h2 className="text-xl font-semibold">AI Health Analysis</h2>
        </div>

        {supported && (
          <div className="flex items-center gap-2">
            <Button
              type="button"
              variant={status === "idle" ? "default" : "secondary"}
              size="sm"
              onClick={handlePrimary}
              className="gap-2"
            >
              {status === "speaking" ? (
                <><Pause className="h-4 w-4" /> Pause</>
              ) : status === "paused" ? (
                <><Play className="h-4 w-4" /> Resume</>
              ) : (
                <><Volume2 className="h-4 w-4" /> Read aloud</>
              )}
            </Button>
            {status !== "idle" && (
              <Button type="button" variant="ghost" size="sm" onClick={stop} className="gap-2" aria-label="Stop">
                <Square className="h-4 w-4" />
              </Button>
            )}
          </div>
        )}
      </div>

      <p className="text-sm text-muted-foreground mb-6">
        Generated by Llama 3.3 70B · Based on your county's specific data
      </p>

      <div className="space-y-4">
        {paragraphs.map((p, i) => (
          <p key={i} className="text-foreground/85 leading-[1.75]">
            {p}
          </p>
        ))}
      </div>

      {!supported && (
        <p className="text-xs text-muted-foreground mt-4">
          Read-aloud isn't supported in this browser.
        </p>
      )}
    </section>
  );
};
